pub mod entries_page;
mod entries_page_bindings;
mod entries_page_cards;
mod entries_page_controls;
mod entries_page_effect;
mod entries_page_groups;
mod entries_page_intent;
mod entries_page_presenter;
mod entries_page_queries;
mod entries_page_reducer;
mod entries_page_runtime;
mod entries_page_state;
pub mod feeds_page;
mod feeds_page_sections;
pub mod reader_page;
mod reader_page_bindings;
mod reader_page_effect;
mod reader_page_intent;
mod reader_page_reducer;
mod reader_page_runtime;
mod reader_page_session;
mod reader_page_state;
mod reader_page_support;
pub mod settings_page;
mod settings_page_appearance;
mod settings_page_preferences;
mod settings_page_save_effect;
mod settings_page_save_runtime;
mod settings_page_save_session;
mod settings_page_save_state;
mod settings_page_sync;
mod settings_page_sync_effect;
mod settings_page_sync_runtime;
mod settings_page_sync_session;
mod settings_page_sync_state;
mod settings_page_themes;
